/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
	],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        'tiber': {
          '50': '#cdf9ed',
          '100': '#b1f7eb',
          '200': '#8df2e4',
          '300': '#53eadd',
          '400': '#21cabe',
          '500': '#13a49d',
          '600': '#128082',
          '700': '#136267',
          '800': '#154b51',
          '900': '#143b42',
          '950': '#082126',
      },
      
        'oasis': {
          '50': '#fffaf0',
          '100': '#fef3d7',
          '200': '#fde3af',
          '300': '#fbce79',
          '400': '#f8ad44',
          '500': '#f6941e',
          '600': '#ea7910',
          '700': '#c15d10',
          '800': '#9d4915',
          '900': '#7f3f15',
          '950': '#491f09',
        },
        'livid-brown': {
          '50': '#f6eef0',
          '100': '#f1e9eb',
          '200': '#e9d8de',
          '300': '#dbbdc7',
          '400': '#c596a7',
          '500': '#b1778c',
          '600': '#9a6073',
          '700': '#814b5e',
          '800': '#693f4f',
          '900': '#573844',
          '950': '#3c202c',
        },
        'alizarin-crimson': {
          '50': '#fff0f2',
          '100': '#ffe1e4',
          '200': '#fec7ce',
          '300': '#fe9faa',
          '400': '#fd6879',
          '500': '#fd354c',
          '600': '#ef253c',
          '700': '#c90d23',
          '800': '#a30f20',
          '900': '#8b1321',
          '950': '#49040d',
        },
        'contessa': {
          '50': '#f9ecec',
          '100': '#f4e2e1',
          '200': '#eecfce',
          '300': '#e4b6b4',
          '400': '#d4908c',
          '500': '#b66d68',
          '600': '#ae534c',
          '700': '#8f433d',
          '800': '#743734',
          '900': '#65332f',
          '950': '#2f1614',
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}